name: ETH Tracker

on:
  schedule:
    - cron: "0 10 * * 1" # Runs every Monday 10:00 UTC
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install node-fetch
      - run: node index.js
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: rewards-csv
          path: rewards.csv
